/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package check.maat;

import models.Board;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Board board = new Board();
        System.out.println(board.getPrintln());
        board.setPrintln("snikkel");
        System.out.println(board.getPrintln());
    }
}

